name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  e2e-tests:
    name: ${{ matrix.os }} - ${{ matrix.bundler }} - ${{ matrix.mode }}
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    # env:
    #   PLAYWRIGHT_DOWNLOAD_HOST: https://cdn.npmmirror.com/binaries/playwright
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest, windows-latest] # Linux cubre Mac para lógica de Node
        #bundler: [webpack, rollup, esbuild]
        #mode: [dev, prod]
        os: [ubuntu-latest] # Linux cubre Mac para lógica de Node
        bundler: [webpack]
        mode: [dev]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Cache Playwright Browsers
        id: playwright-cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.cache/ms-playwright
            ~\AppData\Local\ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      - name: Install Playwright Browsers & Deps (Ubuntu - Cache Miss)
        if: matrix.os == 'ubuntu-latest' && steps.playwright-cache.outputs.cache-hit != 'true'
        timeout-minutes: 10
        run: npx playwright install --with-deps
      - name: Install Playwright Deps Only (Ubuntu - Cache Hit)
        if: matrix.os == 'ubuntu-latest' && steps.playwright-cache.outputs.cache-hit == 'true'
        timeout-minutes: 5
        run: npx playwright install-deps
      - name: Install Playwright Browsers (Windows - Cache Miss)
        if: matrix.os == 'windows-latest' && steps.playwright-cache.outputs.cache-hit != 'true'
        timeout-minutes: 10
        run: npx playwright install
      # Construimos si estamos en modo PROD
      - name: Build App (if prod)
        if: matrix.mode == 'prod'
        run: npm run build:${{ matrix.bundler }}

      # Ejecutamos el test
      - name: Run Playwright Tests
        # Definimos el comando dinámicamente según la matriz
        env:
          TEST_CMD: ${{ matrix.mode == 'dev' && format('npm run dev:{0}', matrix.bundler) || format('npm run start:{0}', matrix.bundler) }}
        run: npx playwright test
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: report-${{ matrix.os }}-${{ matrix.bundler }}-${{ matrix.mode }}
          path: playwright-report/
          retention-days: 30
